### ISSUE TITLE
more docs on SSM fields required for AWS account readiness

### ISSUE THREAD

**Issue by rtyley** [guardian/cdk#1314]
Following the guide at https://github.com/guardian/cdk/blob/main/docs/migration-guide.md#account-readiness, @SHession  & I ran:

```
npx @guardian/cdk@latest account-readiness --profile ophan
```

The tool (added with https://github.com/guardian/cdk/pull/689) is wonderful, but the report on what fields are missing could be even more helpful - this is the output we got:

```
Required parameters are missing: 
  /account/services/anghammarad.topic.arn: SSM parameter containing the ARN of the Anghammarad SNS topic
  /account/services/logging.stream.name: SSM parameter containing the Name (not ARN) on the kinesis stream
  /account/services/access-logging/bucket: S3 bucket to store your access logs
  /account/services/private.config.bucket: SSM parameter containing the S3 bucket name holding the app's private configuration
  /account/vpc/primary/id: Virtual Private Cloud to run EC2 instances within. Should NOT be the account default VPC.
  ...
```

## Could we have explanatory links?

For us on the Ophan team, several of these config values could have done with links to more detailed documentation on how to supply the correct values:

- [ ] `/account/services/anghammarad.topic.arn` - the term '[anghammarad](https://github.com/guardian/anghammarad)' is not actually well known in the wider department (it's also hard to pronounce and not very self-explanatory!), so it could do with a link. What is the SNS Topic for - and what's the recommended way of creating the SNS topic - could this topic, and the SSM parameter, be created by DevX with a StackSet maybe?
- [ ] `/account/services/access-logging/bucket` - quite surprised this is mandatory! In the Ophan account we generally don't  store ELB access logs. Still, we can create a bucket if we need to - what's the recommended way of creating the bucket - cloudformation?
- [ ] `/account/services/private.config.bucket` - should this be mandatory? Ophan doesn't have any apps that load their private config from S3 anymore, as far as I know - we use AWS Parameter Store, which I think is recommended best practice?
- [ ] `/account/vpc/primary/id` - the AWS Ophan account is shared between Data Tech and the Ophan team, each with their own VPC, so choosing the correct Account-wide value for this is a little tricky for us.

**Comment by akash1810** [comment]
## `/account/services/anghammarad.topic.arn`

This should in fact be marked as [optional](https://github.com/guardian/cdk/blob/2b65959b7aadac5e39f0f691c156146c111d1f55/src/constants/ssm-parameter-paths.ts#L4). PRs welcomed!

Anghammarad is a notification service, used to notify the Engineering teams of any issues. Example usages include send messages to teams when a deployment fails, notifying when an AMIgo bake fails. It's fair to say [current usage](https://github.com/search?l=Scala&q=org%3Aguardian+anghammarad&type=Code) is fairly DevX orientated.

> What is the SNS Topic for - and what's the recommended way of creating the SNS topic - could this topic, and the SSM parameter, be created by DevX with a StackSet maybe?

Anghammarad is an SNS triggered lambda. Currently, its designed to have one topic that all accounts have `sns:publish` permissions to. Making this a stack set makes a lot of sense!

## `/account/services/access-logging/bucket`

I think we should make this [optional](https://github.com/guardian/cdk/blob/2b65959b7aadac5e39f0f691c156146c111d1f55/src/constants/ssm-parameter-paths.ts#L4) too whilst the LB logging story is not quite complete - a complete story would be the ingestion of the logs into Central ELK.

## `/account/services/private.config.bucket`

> should this be mandatory? Ophan doesn't have any apps that load their private config from S3 anymore, as far as I know - we use AWS Parameter Store, which I think is recommended best practice?

You're correct; it too should be optional.

## `/account/vpc/primary/id`

> the AWS Ophan account is shared between Data Tech and the Ophan team, each with their own VPC, so choosing the correct Account-wide value for this is a little tricky for us

Intersting! IIRC you're similar to the mobile team in this regard. It's worth noting that this value is the default for a CFN Parameter and can be customised at runtime. This isn't desirable though as the value won't be tracked in VCS - there is a way to achieve this, but I forget how cc @guardian/devx-operations for help.

In the [construct](https://github.com/guardian/cdk/blob/main/src/constructs/vpc/vpc.ts) to create a VPC, we're opinionated on the path being `/account/vpc/<PREFIX>/id` (and `/account/vpc/<PREFIX>/subnets/private` and `/account/vpc/<PREFIX>/subnets/public`).

**Comment by jacobwinch** [comment]
> This isn't desirable though as the value won't be tracked in VCS - there is a way to achieve this, but I forget how cc @guardian/devx-operations for help.

I think you could:

a) Access the parameter in TypeScript (I'm not 100% sure of the syntax for this, but it must be possible) and override the default value
b) Pass in a custom value via `riff-raff.yaml` using [`templateParameters`](https://riffraff.gutools.co.uk/docs/magenta-lib/types#cloudformation) e.g.

```yaml
stacks:
- ophan
regions:
- eu-west-1
deployments:
  cfn:
    type: cloud-formation
    parameters:
      templatePath: cfn.yaml
      templateParameters:
        VpcId: "/account/vpc/ophan/id"
        testguec2appPrivateSubnets: "/account/vpc/ophan/subnets/private" # N.B. the prefix here will be different for your stack, you can get it from the snapshot test
        testguec2appPublicSubnets: "/account/vpc/ophan/subnets/public" # N.B. the prefix here will be different for your stack, you can get it from the snapshot test
```

**Comment by akash1810** [comment]
Achieving GuCDK account-readiness should be a one time thing, and after discussions we think it's easier and more correct for DevX to run this process. That is, DevX will take responsibility to ensuring an AWS account is of the correct shape.

We've created https://github.com/guardian/aws-account-setup to help here, and we should add the Ophan account to it. Closing this issue.

**Comment by rtyley** [comment]
> Achieving GuCDK account-readiness should be a one time thing, and after discussions we think it's easier and more correct for DevX to run this process. That is, DevX will take responsibility to ensuring an AWS account is of the correct shape.

Ah, ok that does make sense - sounds good to me. As it happens, I'm in the process of helping out the Ophan team with [a new Lambda](https://github.com/guardian/ophan-google-search-index-checker), and we were looking at whether we could install it using CDK or not - just so you know, I just re-ran `account-readiness` on the Ophan account, and got these remaining outstanding issues, which match the [guardian/aws-account-setup status report for Ophan](https://github.com/guardian/aws-account-setup/blob/main/status-report.md#ophan-account):

```
Required parameters are missing:
  /account/services/access-logging/bucket: S3 bucket to store your access logs
  /account/services/private.config.bucket: SSM parameter containing the S3 bucket name holding the app's private configuration
  /account/vpc/primary/subnets/private: A comma-separated list of private subnets
```

From your description [above](https://github.com/guardian/cdk/issues/1314#issuecomment-1140835595), the first two should probably be optional?

It would be nice to start using CDK in the Ophan account with this new lambda, is it possible to use CDK without passing all account-readiness checks?

**Comment by akash1810** [comment]
@rtyley we've changed approach a little; DevX will take responsibility of getting accounts GuCDK ready (via https://github.com/guardian/aws-account-setup). We're slowly making [progress](https://github.com/guardian/aws-account-setup/blob/main/status-report.md) on this, and should be able to prioritise the Ophan account. Would you have time to pair next week?

(cc @guardian/devx-operations)
