### ISSUE TITLE
GuEc2App cannot differentiate between apps with different domains

### ISSUE THREAD

**Issue by jonathonherbert** [guardian/cdk#850]
At the moment, it looks there's only one namespace per stack for mappings produced by the GuEc2App pattern. When `synth`ing [this CDK](https://github.com/guardian/typerighter/blob/fb6cb1ad7e084ff8020b30515e590028ae8a51e3/cdk/lib/index.ts), with two apps with different certificates, the current output is:

```json
"stagemapping": {
  "CODE": {
    "domainName": "checker.typerighter.code.dev-gutools.co.uk",
    "minInstances": 1,
    "maxInstances": 2
  },
  "PROD": {
    "domainName": "checker.typerighter.gutools.co.uk",
    "minInstances": 3,
    "maxInstances": 6
  }
}
```

We'd expect space for two apps here (the other is `manager.typerighter.gutools.co.uk`), but it looks like we're missing a dimension to express that, and as a result the last app declaration wins – if I swap the order of the declared apps, I get `manager` in the map above, with no mention of a `checker`.

**Comment by jacobwinch** [comment]
> Not sure if @jacobwinch had explored this in the past?

No, I think is just an oversight on my part (I haven't worked on many multi-app stacks before!). Thanks for reporting the problem @jonathonherbert!

> I think the most sensible change here would be to rename "stagemapping" to the app name

I really like this suggestion @akash1810 👍

**Comment by akash1810** [comment]
Been thinking about this a little and I think it's more correct to follow the SSA (stack, stage, app) specificity format in this mapping. That is have a mapping that looks like this:

```json
"CODE": {
  "checker": {
    "domainName": "checker.typerighter.code.dev-gutools.co.uk",
    "minInstances": 1,
    "maxInstances": 2
  },
  "manager": {
    "domainName": "manager.typerighter.code.dev-gutools.co.uk",
    "minInstances": 1
    "maxInstances": 2
  }
},
"PROD": {
  "checker": {
    "domainName": "checker.typerighter.gutools.co.uk",
    "minInstances": 3,
    "maxInstances": 6
  },
  "manager": {
    "domainName": "manager.typerighter.gutools.co.uk",
    "minInstances": 3,
    "maxInstances": 6
  }
}
```

The interface GuCDK provides would look largely the same as it does today. I think this change should make it easier to become more lenient on the values of `stage`, which will benefit infra stacks or stacks like CAPI's.
